import { memberOperationFormAction } from "@/modules/clubs/presentation/member-actions";
import { MemberProvisionForm } from "@/modules/clubs/presentation/member-provision-form";
import { SupabaseMemberOperationsReader } from "@/modules/clubs/infrastructure/supabase-member-operations-reader";
import { requireSession } from "@/shared/auth/session";
import { ActionResult } from "@/shared/ui/action-result";
import { EmptyState } from "@/shared/ui/empty-state";
import { PageHeader } from "@/shared/ui/page-header";
import { SubmitButton } from "@/shared/ui/submit-button";
import { DestructiveConfirmation } from "@/shared/ui/destructive-confirmation";

export default async function MembersPage({ searchParams }: { searchParams: Promise<{ message?: string; error?: string }> }) {
  const actor = await requireSession(); const reader = new SupabaseMemberOperationsReader(); const [model, notice] = await Promise.all([reader.forActor(actor.id), searchParams]);
  const club = model.directed[0];
  return <><PageHeader title="Miembros y unidades" description="Gestione la membresía solo dentro de su alcance autorizado." />
    {notice.message ? <ActionResult kind="success" message="La operación se completó." /> : null}{notice.error ? <ActionResult kind="error" message="No fue posible completar la operación. Verifique los datos e intente nuevamente." /> : null}
    {club ? <section className="stack"><h2>Registrar miembro</h2><MemberProvisionForm clubId={club.id} units={club.units}/>
      <form className="card form-stack" action={memberOperationFormAction}><input type="hidden" name="operation" value="unit"/><input type="hidden" name="clubId" value={club.id}/><label htmlFor="unit-name">Nueva unidad</label><input id="unit-name" name="name" required maxLength={160}/><SubmitButton pendingLabel="Creando…">Crear unidad</SubmitButton></form>
      <h2>Remediación pendiente</h2>{club.pending.length === 0 ? <EmptyState title="No hay membresías pendientes"/> : club.pending.map(member => <form className="card form-stack" action={memberOperationFormAction} key={member.id}><input type="hidden" name="operation" value="remediate"/><input type="hidden" name="memberId" value={member.id}/><strong>{member.fullName}</strong><label>Nombre completo<input name="fullName" defaultValue={member.fullName} required/></label><label>Fecha de nacimiento<input name="dateOfBirth" type="date" required/></label><label>Unidad<select name="unitId">{club.units.map(unit => <option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></label><SubmitButton pendingLabel="Completando…">Completar remediación</SubmitButton></form>)}</section> : null}
    {model.directed.map(club => <section className="stack" key={club.id}><h2>{club.name}</h2>{club.members.map(member => <article className="card stack" key={member.id}><h3>{member.fullName} · {member.condition === "LEADER" ? "Líder" : "Conquistador"}</h3><p>{member.lifecycle === "ACTIVE" ? `Unidad: ${member.unitName ?? "sin unidad"}` : "Membresía pendiente o retirada"}</p>{club.units.length ? <form action={memberOperationFormAction}><input type="hidden" name="operation" value="transfer"/><input type="hidden" name="memberId" value={member.id}/><label>Trasladar a <select name="unitId">{club.units.map(unit => <option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></label><SubmitButton pendingLabel="Trasladando…">Trasladar</SubmitButton></form> : null}<form action={memberOperationFormAction}><input type="hidden" name="operation" value="assign"/><input type="hidden" name="memberId" value={member.id}/><label>Asignar rol <select name="role"><option value="INSTRUCTOR">Instructor · varias unidades</option><option value="COUNSELOR">Consejero · una unidad</option></select></label><select name="unitId">{club.units.map(unit => <option key={unit.id} value={unit.id}>{unit.name}</option>)}</select><SubmitButton pendingLabel="Asignando…">Asignar</SubmitButton></form>{member.assignments.map(assignment => <form action={memberOperationFormAction} key={assignment.id}><input type="hidden" name="operation" value="revoke"/><input type="hidden" name="assignmentId" value={assignment.id}/><span>{assignment.role} · {assignment.unitName} </span><SubmitButton pendingLabel="Quitando…">Quitar rol</SubmitButton></form>)}<DestructiveConfirmation summary="Retirar miembro"><form action={memberOperationFormAction}><input type="hidden" name="operation" value="withdraw"/><input type="hidden" name="memberId" value={member.id}/><p>Se revocará el acceso operativo y se conservará el historial.</p><SubmitButton pendingLabel="Retirando…">Confirmar retiro</SubmitButton></form></DestructiveConfirmation></article>)}</section>)}
    {model.rotations.length ? <section className="stack"><h2>Rotación de dirección</h2><p>Sólo administración del sistema; no incluye tarjetas, avance ni evidencia.</p>{model.rotations.map(rotation => <form className="card form-stack" action={memberOperationFormAction} key={rotation.clubId}><input type="hidden" name="operation" value="rotate"/><input type="hidden" name="clubId" value={rotation.clubId}/><p>{rotation.clubName} · Dirección actual: {rotation.directorName}</p><label>Sucesor<select name="memberId">{rotation.successors.map(member => <option key={member.id} value={member.id}>{member.fullName}</option>)}</select></label><label>Motivo de la rotación<textarea name="reason" minLength={3} maxLength={500} required/></label><SubmitButton pendingLabel="Rotando…">Confirmar rotación</SubmitButton></form>)}</section> : null}
  </>;
}
